# Configurações do seu usuário GitHub (substitua onde indicado)
owner: lucasbalbino10  # <-- Coloque seu usuário do GitHub aqui
repo: verificacaodedominio      # <-- Coloque o nome do repo (ex: uptime-monitor)

user-agent: "UptimeMonitor/1.0 (https://github.com/lucasbalbino10/verificacaodedominio)"

# Lista de sites para monitorar
sites:
  - name: Esus Arara Cloud
    url: https://esusarara.cloud

  - name: Admin Noxx
    url: https://admin.noxx.pro

  - name: Registra Ponto
    url: https://registraponto.com/ponto
    method: GET # Garante que ele verifique a página específica

  - name: PPCE Noxx
    url: https://ppce.euestudei.com

# Configuração da Página de Status Visual
status-website:
  # O domínio onde a página de status vai aparecer
  cname: status.noxx.pro
  
  # Textos da página
  name: Status dos Sistemas Noxx
  introTitle: "**Monitoramento em Tempo Real**"
  introMessage: "Acompanhe aqui a disponibilidade e performance dos nossos sistemas."
  
  # (Opcional) Links para aparecerem no topo da página
  navbar:
    - title: Site Principal
      href: https://noxx.pro
    - title: Suporte
      href: https://noxx.pro/contato

# (Opcional) Se for usar notificações via n8n ou CallMeBot, deixe assim:
# Lembre-se de adicionar o "secret" NOTIFICATION_WEBHOOK_URL no GitHub
notifications:
  type: webhook
